version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: liht
      POSTGRES_PASSWORD: BulbaXD
      POSTGRES_DB: weather
    ports:
      - "5432:5432"

  bot:
    build: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - postgres